### ISSUE TITLE
README tutorial link forwards to invalid site

### ISSUE THREAD

**Issue by dfxe** [the-javapocalypse/Python-File-Encryptor#3]
When using the tutorial link in the readme file, it redirects to another website (might be malicious?).

**Comment by EZRAIDv2** [comment]
Yeah.

**Comment by YoshithaRathnayake** [comment]
> When using the tutorial link in the readme file, it redirects to another website (might be malicious?).

Shall I work on this ?

**Comment by uKruel** [comment]
Yes please

**Comment by FreyGeospatial** [comment]
This is still an issue. Text-based tutorial link does not go to correct page.

**Comment by YoshithaRathnayake** [comment]
> Yes please

Can you send me the tutorial link @dfxe I'll work on this

**Comment by dfxe** [comment]
I've found the video on [youtube](https://www.youtube.com/watch?v=UB2VX4vNUa0) @YoshithaRathnayake

**Comment by YoshithaRathnayake** [comment]
> I've found the video [here on youtube](https://www.youtube.com/watch?v=UB2VX4vNUa0) @YoshithaRathnayake

I asked for the tutorial link that should redirect from the readme @dfxe

**Comment by dfxe** [comment]
The link redirects to a page (letscodepro.com/encryption-in-python-using-pycrypto) that is no longer being maintained. However, the youtube video from that page is still there. Using the link to the youtube video should do the trick. @YoshithaRathnayake

**Comment by YoshithaRathnayake** [comment]
> The link redirects to a page (letscodepro.com/encryption-in-python-using-pycrypto) that is no longer being maintained. However, the youtube video from that page is still there. Using the link to the youtube video should do the trick. @YoshithaRathnayake

So I should insert the given link to here right? @dfxe 

![image](https://user-images.githubusercontent.com/97069900/209691321-115ca867-4f1f-4a3b-aed1-2b457cd39856.png)
